### ISSUE TITLE
Is burstware affiliated with the developers of react-native-paper?

### ISSUE THREAD

**Issue by leecommamichael** [burstware/react-native-portal#2]
I need a portal implementation. 

This package seems to be the same code as found in [react-native-paper](https://github.com/callstack/react-native-paper/blob/master/src/components/Portal/Portal.tsx)'s implementation of Portals, even the comments are identical. Are you the same group of developers that maintain that code? Is it planned for react-native-paper to consume this library?

**Comment by JBaczuk** [comment]
No Burstware is not affiliated with React Native Paper, just found the portal component useful, so separated it out into it's own module and transpiled to javascript.
