### ISSUE TITLE
Message from React-Native-Paper maintainers

### ISSUE THREAD

**Issue by Trancever** [burstware/react-native-portal#3]
Hello, [react-native-paper](https://github.com/callstack/react-native-paper) maintainer here 👋 

First of all, we are extremely happy that people find our code/implementation useful, it means a lot to us!

We release our library under the [MIT](https://github.com/callstack/react-native-paper/blob/main/LICENSE.md) license which means we are completely fine with other people using, changing, and publishing it, but when they do it 1 to 1 without changing any line of the code, it seems a bit unfair. It's especially unfair to all the people who contributed to the `Portal` component implementation.

We think it would be nice from you to at least give credits to [react-native-paper](https://github.com/callstack/react-native-paper) library.

**Comment by JBaczuk** [comment]
@Trancever Good to hear from you! Please submit a PR with the credits you would like and I'll be happy to merge.

**Comment by JBaczuk** [comment]
Added this, lmk if you need anything else: https://github.com/burstware/react-native-portal/commit/471b19c762285cc67585c6a4902d6c1cdf32504f
